Queued Screen UI
niketmm/android-download-manager pull request #11
Opened 2021-11-05 11:22 UTC by niketmm

In this branch we are covering the UI for the Queue Screen along with little Clean Arch setup. 
We will use lazyColumn to display number of items in the QueuedScreen.

2021-11-08 07:42 UTC, aditya-bhawsar-mm requested changes

2021-11-08 07:42 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/TabLayoutMain.kt
>  import androidx.compose.material.*
avoid using wildcard imports please

2021-11-08 07:42 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/ItemComponent.kt
> +                    contentDescription = "Pause ImageButton"
instead of hardcoding use a string resource for this

2021-11-08 07:42 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/ItemComponent.kt
> +            Image(imageVector = Icons.Default.Tv, contentDescription = "Tv ImageButton")
use a string resource here in content description and everywhere you are using the same

2021-11-08 07:42 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
> +//    val pagerState = rememberPagerState(tabs.size)
get rid of this comment if you can please

2021-11-09 07:17 UTC, aditya-bhawsar-mm approved these changes

2021-11-15 08:56 UTC, aditya-bhawsar-mm requested changes

2021-11-15 08:56 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>  import androidx.compose.runtime.*
remove wildcard import

2021-11-15 08:56 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/ItemComponent.kt
> +                fontSize = 12.sp
move hardcoded values to dimens file

2021-11-15 10:00 UTC, niketmm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/ItemComponent.kt
> +                fontSize = 12.sp
how can we add those `sp` dimension files?  @aditya-bhawsar-mm 
We can add it to the dimensions but fields like TextField are then showing errors.

2021-11-16 07:50 UTC, aditya-bhawsar-mm approved these changes

2021-11-17 09:35 UTC, merged