TabLayout with Pager
niketmm/android-download-manager pull request #9
Opened 2021-11-05 06:57 UTC by niketmm

- Added Tab Layouts to the Main Screen 
 - Added Pager for the TabLayout 
 - Added various Screens

2021-11-09 07:34 UTC, aditya-bhawsar-mm requested changes

2021-11-09 07:34 UTC, aditya-bhawsar-mm commented on buildSrc/src/main/java/Versions.kt
> +    const val coreKtx = "1.6.0"
follow kotlin conventions for const

2021-11-09 07:34 UTC, aditya-bhawsar-mm commented on buildSrc/src/main/java/AppDependencies.kt
> +    private const val kotlinStdLib = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Versions.kotlin}"
follow kotlin conventions for the values that are const

2021-11-09 07:34 UTC, aditya-bhawsar-mm commented on buildSrc/src/main/java/AppConfig.kt
> +const val compileSdk = 31
follow kotlin code conventions (i.e. const variables are to be named with a underscore and in uppercase)

2021-11-09 07:34 UTC, aditya-bhawsar-mm commented on build.gradle.kts
> +        classpath("com.android.tools.build:gradle:7.0.3")
use versions value from buildSrc if possible

2021-11-09 07:34 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>              onDismissRequest = { openDialog.value = false },
is there not content for displaying custom alert dialog why is the content inside text ?

2021-11-09 07:34 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>              onDismissRequest = { openDialog.value = false },
its a voilation for the component to change its own state do this with functions passed as parameters

2021-11-09 08:25 UTC, niketmm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>              onDismissRequest = { openDialog.value = false },
The Alert Dialog is being added by @NikhilChauhan4  
We can make those changes to his branch so that it get reflected to other child branches also. 
( I guess it has been added to dev branch also 😓 )

2021-11-09 09:37 UTC, niketmm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>              onDismissRequest = { openDialog.value = false },
I didn't understand this part? 
Inside text? If you asking why the Column inside text parameter than: 
Actually this is the only way we can show or have custom views for our Alert Dialog Box or if there are better ways to achieve this share this with @NikhilChauhan4 and me

2021-11-09 13:44 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>              onDismissRequest = { openDialog.value = false },
its ok if thats the case

2021-11-09 13:45 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>              onDismissRequest = { openDialog.value = false },
make the changes any way will give you practice and merging the prs will remove it from dev when you do

2021-11-10 09:12 UTC, niketmm commented on app/src/main/java/com/mutualmobile/admclone/MainActivity.kt
>              onDismissRequest = { openDialog.value = false },
I have made those changes you can have a look 
if everything has been implemented in right way or not.

2021-11-10 09:13 UTC, niketmm commented on buildSrc/src/main/java/Versions.kt
> +    const val coreKtx = "1.6.0"
Should we do this constant convention changes at every PR? 
or at the Parent pr?

2021-11-15 08:54 UTC, aditya-bhawsar-mm requested changes

2021-11-15 08:54 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/CustomDialogBox.kt
> +                Spacer(modifier = Modifier.padding(bottom = 8.dp))
move these values to dimensions file rather than hardcoding

2021-11-15 08:54 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/CustomDialogBox.kt
> +                    Text(text = "Submit")
move hardcoded text to strings file

2021-11-15 08:54 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/TabItem.kt
> +sealed class TabItem(var title: String, var screen: ComposableFun) {
replace string with a @StringRes Int

2021-11-15 08:54 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/screen/FinishedScreen.kt
> +            text = "Finished Screen",
hardcoded string

2021-11-15 08:54 UTC, aditya-bhawsar-mm commented on buildSrc/src/main/java/AppDependencies.kt
> +    private const val COMPOSE_LIFECYCLE = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
move the value to versions file

2021-11-15 08:54 UTC, aditya-bhawsar-mm commented on buildSrc/src/main/java/AppDependencies.kt
> +    private const val JETPACK_JUNIT = "androidx.compose.ui:ui-test-junit4:${COMPOSE}"
please use Version.Compose rather than Compose also remove the import

2021-11-15 10:38 UTC, niketmm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/TabItem.kt
> +sealed class TabItem(var title: String, var screen: ComposableFun) {
This is causing more errors here

2021-11-16 07:54 UTC, aditya-bhawsar-mm requested changes

2021-11-16 07:54 UTC, aditya-bhawsar-mm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/TabItem.kt
> +sealed class TabItem(var title: String, var screen: ComposableFun) {
what kind of error?

you can use the int value while passing a string resource in text widget

2021-11-17 06:42 UTC, niketmm commented on app/src/main/java/com/mutualmobile/admclone/presentation/main/component/TabItem.kt
> +sealed class TabItem(var title: String, var screen: ComposableFun) {
I have done the changes it was easy 
Now there are no errors

2021-11-17 07:48 UTC, aditya-bhawsar-mm approved these changes

2021-11-17 10:31 UTC, merged